### ISSUE TITLE
DigitalIn can sometimes go into a mode where it flickers on and off

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#98]
it seems to get into a looping situation where it is feeding back on itself and all other widgets on the stage seem to do the same, where they rapidly switch from what they should reading to seeing previous values. Here are the steps:

* Add an AnalogIn
* Add AnalogOut and connect AnalogIn to AnalogOut
* Add Digital
* Rapidly send on/off from your switch to the DigitalIn port (doesn't always work)

After a minute or so, it will start bouncing from 0-1023 on it’s own and the AnalogIn and AnalogOut will seem to be stuck on their previous values even when you change the actual potentiometer. 

Switching to a different server mode seems to stop the problem, but rapidly sending on/off to the DigitalIn port causes the problem to start again.

**Comment by scazan** [comment]
Try out the latest pull. I made an optimization that may prevent this from
happening. The model is getting into an infinite loop because it is not
syncing itself before sending data to the server model. This resulted in an
oscillation.

On Fri, Dec 11, 2015 at 5:06 PM, Philip van Allen <notifications@github.com>
wrote:

> Assigned #98 <https://github.com/netlabtoolkit/ntk/issues/98> to @scazan
> <https://github.com/scazan>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netlabtoolkit/ntk/issues/98#event-489950354>.
>



-- 
Scott
http://www.scottcazan.com
https://soundcloud.com/scottcazan
Twitter: @scazan
